// <auto-generated/>
using Honlsoft.Chess.ChessDotCom.Models;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Honlsoft.Chess.ChessDotCom.Player.Item.Stats {
    public class StatsGetResponse : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The chess960_daily property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Honlsoft.Chess.ChessDotCom.Models.Stats? Chess960Daily { get; set; }
#nullable restore
#else
        public Honlsoft.Chess.ChessDotCom.Models.Stats Chess960Daily { get; set; }
#endif
        /// <summary>The chess_blitz property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Honlsoft.Chess.ChessDotCom.Models.Stats? ChessBlitz { get; set; }
#nullable restore
#else
        public Honlsoft.Chess.ChessDotCom.Models.Stats ChessBlitz { get; set; }
#endif
        /// <summary>The chess_bullet property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Honlsoft.Chess.ChessDotCom.Models.Stats? ChessBullet { get; set; }
#nullable restore
#else
        public Honlsoft.Chess.ChessDotCom.Models.Stats ChessBullet { get; set; }
#endif
        /// <summary>The chess_daily property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Honlsoft.Chess.ChessDotCom.Models.Stats? ChessDaily { get; set; }
#nullable restore
#else
        public Honlsoft.Chess.ChessDotCom.Models.Stats ChessDaily { get; set; }
#endif
        /// <summary>The chess_rapid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Honlsoft.Chess.ChessDotCom.Models.Stats? ChessRapid { get; set; }
#nullable restore
#else
        public Honlsoft.Chess.ChessDotCom.Models.Stats ChessRapid { get; set; }
#endif
        /// <summary>The fide property</summary>
        public int? Fide { get; set; }
        /// <summary>The puzzle_rush property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public StatsGetResponse_puzzle_rush? PuzzleRush { get; set; }
#nullable restore
#else
        public StatsGetResponse_puzzle_rush PuzzleRush { get; set; }
#endif
        /// <summary>The tactics property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public StatsGetResponse_tactics? Tactics { get; set; }
#nullable restore
#else
        public StatsGetResponse_tactics Tactics { get; set; }
#endif
        /// <summary>
        /// Instantiates a new statsGetResponse and sets the default values.
        /// </summary>
        public StatsGetResponse() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static StatsGetResponse CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new StatsGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"chess960_daily", n => { Chess960Daily = n.GetObjectValue<Honlsoft.Chess.ChessDotCom.Models.Stats>(Honlsoft.Chess.ChessDotCom.Models.Stats.CreateFromDiscriminatorValue); } },
                {"chess_blitz", n => { ChessBlitz = n.GetObjectValue<Honlsoft.Chess.ChessDotCom.Models.Stats>(Honlsoft.Chess.ChessDotCom.Models.Stats.CreateFromDiscriminatorValue); } },
                {"chess_bullet", n => { ChessBullet = n.GetObjectValue<Honlsoft.Chess.ChessDotCom.Models.Stats>(Honlsoft.Chess.ChessDotCom.Models.Stats.CreateFromDiscriminatorValue); } },
                {"chess_daily", n => { ChessDaily = n.GetObjectValue<Honlsoft.Chess.ChessDotCom.Models.Stats>(Honlsoft.Chess.ChessDotCom.Models.Stats.CreateFromDiscriminatorValue); } },
                {"chess_rapid", n => { ChessRapid = n.GetObjectValue<Honlsoft.Chess.ChessDotCom.Models.Stats>(Honlsoft.Chess.ChessDotCom.Models.Stats.CreateFromDiscriminatorValue); } },
                {"fide", n => { Fide = n.GetIntValue(); } },
                {"puzzle_rush", n => { PuzzleRush = n.GetObjectValue<StatsGetResponse_puzzle_rush>(StatsGetResponse_puzzle_rush.CreateFromDiscriminatorValue); } },
                {"tactics", n => { Tactics = n.GetObjectValue<StatsGetResponse_tactics>(StatsGetResponse_tactics.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<Honlsoft.Chess.ChessDotCom.Models.Stats>("chess960_daily", Chess960Daily);
            writer.WriteObjectValue<Honlsoft.Chess.ChessDotCom.Models.Stats>("chess_blitz", ChessBlitz);
            writer.WriteObjectValue<Honlsoft.Chess.ChessDotCom.Models.Stats>("chess_bullet", ChessBullet);
            writer.WriteObjectValue<Honlsoft.Chess.ChessDotCom.Models.Stats>("chess_daily", ChessDaily);
            writer.WriteObjectValue<Honlsoft.Chess.ChessDotCom.Models.Stats>("chess_rapid", ChessRapid);
            writer.WriteIntValue("fide", Fide);
            writer.WriteObjectValue<StatsGetResponse_puzzle_rush>("puzzle_rush", PuzzleRush);
            writer.WriteObjectValue<StatsGetResponse_tactics>("tactics", Tactics);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
