// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Honlsoft.Chess.ChessDotCom.Player.Item.Stats {
    public class StatsGetResponse_puzzle_rush_best : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The score property</summary>
        public int? Score { get; set; }
        /// <summary>The total_attempts property</summary>
        public int? TotalAttempts { get; set; }
        /// <summary>
        /// Instantiates a new statsGetResponse_puzzle_rush_best and sets the default values.
        /// </summary>
        public StatsGetResponse_puzzle_rush_best() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static StatsGetResponse_puzzle_rush_best CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new StatsGetResponse_puzzle_rush_best();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"score", n => { Score = n.GetIntValue(); } },
                {"total_attempts", n => { TotalAttempts = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("score", Score);
            writer.WriteIntValue("total_attempts", TotalAttempts);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
