// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Honlsoft.Chess.ChessDotCom.Player.Item.Stats {
    public class StatsGetResponse_puzzle_rush : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The best property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public StatsGetResponse_puzzle_rush_best? Best { get; set; }
#nullable restore
#else
        public StatsGetResponse_puzzle_rush_best Best { get; set; }
#endif
        /// <summary>
        /// Instantiates a new statsGetResponse_puzzle_rush and sets the default values.
        /// </summary>
        public StatsGetResponse_puzzle_rush() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static StatsGetResponse_puzzle_rush CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new StatsGetResponse_puzzle_rush();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"best", n => { Best = n.GetObjectValue<StatsGetResponse_puzzle_rush_best>(StatsGetResponse_puzzle_rush_best.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<StatsGetResponse_puzzle_rush_best>("best", Best);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
