// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Honlsoft.Chess.ChessDotCom.Models {
    public class Stats_tournament : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The count property</summary>
        public int? Count { get; set; }
        /// <summary>The highest_finish property</summary>
        public int? HighestFinish { get; set; }
        /// <summary>The points property</summary>
        public int? Points { get; set; }
        /// <summary>The withdraw property</summary>
        public int? Withdraw { get; set; }
        /// <summary>
        /// Instantiates a new stats_tournament and sets the default values.
        /// </summary>
        public Stats_tournament() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Stats_tournament CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Stats_tournament();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"count", n => { Count = n.GetIntValue(); } },
                {"highest_finish", n => { HighestFinish = n.GetIntValue(); } },
                {"points", n => { Points = n.GetIntValue(); } },
                {"withdraw", n => { Withdraw = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("count", Count);
            writer.WriteIntValue("highest_finish", HighestFinish);
            writer.WriteIntValue("points", Points);
            writer.WriteIntValue("withdraw", Withdraw);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
