// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Honlsoft.Chess.ChessDotCom.Models {
    public class Stats_record : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The draw property</summary>
        public int? Draw { get; set; }
        /// <summary>The loss property</summary>
        public int? Loss { get; set; }
        /// <summary>The win property</summary>
        public int? Win { get; set; }
        /// <summary>
        /// Instantiates a new stats_record and sets the default values.
        /// </summary>
        public Stats_record() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Stats_record CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Stats_record();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"draw", n => { Draw = n.GetIntValue(); } },
                {"loss", n => { Loss = n.GetIntValue(); } },
                {"win", n => { Win = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("draw", Draw);
            writer.WriteIntValue("loss", Loss);
            writer.WriteIntValue("win", Win);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
