// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Honlsoft.Chess.ChessDotCom.Player.Item.Games.Item.Item {
    public class WithMonthGetResponse_games : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The black property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public WithMonthGetResponse_games_black? Black { get; set; }
#nullable restore
#else
        public WithMonthGetResponse_games_black Black { get; set; }
#endif
        /// <summary>The end_time property</summary>
        public int? EndTime { get; set; }
        /// <summary>The fen property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Fen { get; set; }
#nullable restore
#else
        public string Fen { get; set; }
#endif
        /// <summary>The initial_setup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InitialSetup { get; set; }
#nullable restore
#else
        public string InitialSetup { get; set; }
#endif
        /// <summary>The pgn property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pgn { get; set; }
#nullable restore
#else
        public string Pgn { get; set; }
#endif
        /// <summary>The rated property</summary>
        public bool? Rated { get; set; }
        /// <summary>The rules property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Rules { get; set; }
#nullable restore
#else
        public string Rules { get; set; }
#endif
        /// <summary>The start_time property</summary>
        public int? StartTime { get; set; }
        /// <summary>The tcn property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tcn { get; set; }
#nullable restore
#else
        public string Tcn { get; set; }
#endif
        /// <summary>The time_class property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeClass { get; set; }
#nullable restore
#else
        public string TimeClass { get; set; }
#endif
        /// <summary>The time_control property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeControl { get; set; }
#nullable restore
#else
        public string TimeControl { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The uuid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uuid { get; set; }
#nullable restore
#else
        public string Uuid { get; set; }
#endif
        /// <summary>The white property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public WithMonthGetResponse_games_white? White { get; set; }
#nullable restore
#else
        public WithMonthGetResponse_games_white White { get; set; }
#endif
        /// <summary>
        /// Instantiates a new WithMonthGetResponse_games and sets the default values.
        /// </summary>
        public WithMonthGetResponse_games() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static WithMonthGetResponse_games CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new WithMonthGetResponse_games();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"black", n => { Black = n.GetObjectValue<WithMonthGetResponse_games_black>(WithMonthGetResponse_games_black.CreateFromDiscriminatorValue); } },
                {"end_time", n => { EndTime = n.GetIntValue(); } },
                {"fen", n => { Fen = n.GetStringValue(); } },
                {"initial_setup", n => { InitialSetup = n.GetStringValue(); } },
                {"pgn", n => { Pgn = n.GetStringValue(); } },
                {"rated", n => { Rated = n.GetBoolValue(); } },
                {"rules", n => { Rules = n.GetStringValue(); } },
                {"start_time", n => { StartTime = n.GetIntValue(); } },
                {"tcn", n => { Tcn = n.GetStringValue(); } },
                {"time_class", n => { TimeClass = n.GetStringValue(); } },
                {"time_control", n => { TimeControl = n.GetStringValue(); } },
                {"url", n => { Url = n.GetStringValue(); } },
                {"uuid", n => { Uuid = n.GetStringValue(); } },
                {"white", n => { White = n.GetObjectValue<WithMonthGetResponse_games_white>(WithMonthGetResponse_games_white.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<WithMonthGetResponse_games_black>("black", Black);
            writer.WriteIntValue("end_time", EndTime);
            writer.WriteStringValue("fen", Fen);
            writer.WriteStringValue("initial_setup", InitialSetup);
            writer.WriteStringValue("pgn", Pgn);
            writer.WriteBoolValue("rated", Rated);
            writer.WriteStringValue("rules", Rules);
            writer.WriteIntValue("start_time", StartTime);
            writer.WriteStringValue("tcn", Tcn);
            writer.WriteStringValue("time_class", TimeClass);
            writer.WriteStringValue("time_control", TimeControl);
            writer.WriteStringValue("url", Url);
            writer.WriteStringValue("uuid", Uuid);
            writer.WriteObjectValue<WithMonthGetResponse_games_white>("white", White);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
