// <auto-generated/>
using Honlsoft.Chess.ChessDotCom.Titled.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Honlsoft.Chess.ChessDotCom.Titled {
    /// <summary>
    /// Builds and executes requests for operations under \titled
    /// </summary>
    public class TitledRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the Honlsoft.Chess.ChessDotCom.titled.item collection</summary>
        /// <param name="position">The title of the player</param>
        public WithTitleItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("title", position);
            return new WithTitleItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new TitledRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TitledRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/titled", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new TitledRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TitledRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/titled", rawUrl) {
        }
    }
}
