// <auto-generated/>
using Honlsoft.Chess.ChessDotCom.Player.Item.Games.Archives;
using Honlsoft.Chess.ChessDotCom.Player.Item.Games.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Honlsoft.Chess.ChessDotCom.Player.Item.Games {
    /// <summary>
    /// Builds and executes requests for operations under \player\{username}\games
    /// </summary>
    public class GamesRequestBuilder : BaseRequestBuilder {
        /// <summary>The archives property</summary>
        public ArchivesRequestBuilder Archives { get =>
            new ArchivesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Honlsoft.Chess.ChessDotCom.player.item.games.item collection</summary>
        /// <param name="position">The year of the archive</param>
        public WithYearItemRequestBuilder this[int position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("year", position);
            return new WithYearItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>Gets an item from the Honlsoft.Chess.ChessDotCom.player.item.games.item collection</summary>
        /// <param name="position">The year of the archive</param>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public WithYearItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("year", position);
            return new WithYearItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new GamesRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GamesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/player/{username}/games", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new GamesRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GamesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/player/{username}/games", rawUrl) {
        }
    }
}
