openapi: 3.0.3
info:
  title: Chess.com API
  description: The Chess.com API provides read and write access to various data
    on the Chess.com site.
  version: 1.0.0
servers:
  - url: https://api.chess.com/pub
    description: Chess.com API server
externalDocs:
  description: Chess.com API Docs
  url: https://www.chess.com/news/view/published-data-api
paths:
  /player/{username}:
    get:
      summary: Get player information
      description: Get player information
      operationId: getPlayer
      parameters:
        - name: username
          in: path
          description: The username of the player
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  player_id:
                    type: integer
                  url:
                    type: string
                  name:
                    type: string
                  username:
                    type: string
                  title:
                    type: string
                  followers:
                    type: integer
                  country:
                    type: string
                  location:
                    type: string
                  last_online:
                    type: integer
                  joined:
                    type: integer
                  status:
                    type: string
                  is_streamer:
                    type: boolean
                  twitch_url:
                    type: string
                  fide:
                    type: integer
                  avatar:
                    type: string
                  "@id":
                    type: string
  
  /player/{username}/games/archives:
    get:
      summary: List of monthly archives available for the user.
      parameters:
        - name: username
          in: path
          description: The username of the player
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  archives:
                    type: array
                    items:
                      type: string
  /titled/{title}:
    get:
      summary: Get list of players with a given title
      description: Get list of players with a given title
      operationId: getTitledPlayers
      parameters:
        - name: title
          in: path
          description: The title of the player
          required: true
          schema:
            type: string
            enum:
              - GM
              - WGM
              - IM
              - WIM
              - FM
              - WFM
              - NM
              - WNM
              - CM
              - WCM
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  players:
                    type: array
                    items:
                      type: string
  /player/{username}/stats:
    get:
      summary: Get player stats
      description: Get player stats
      operationId: getPlayerStats
      parameters:
        - name: username
          in: path
          description: The username of the player
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  chess_daily:
                    $ref: '#/components/schemas/stats'
                  chess960_daily:
                    $ref: '#/components/schemas/stats'
                  chess_rapid:
                    $ref: '#/components/schemas/stats'
                  chess_bullet:
                    $ref: '#/components/schemas/stats'
                  chess_blitz:
                    $ref: '#/components/schemas/stats'
                  fide:
                    type: integer
                  tactics:
                    type: object
                    properties: 
                      highest:
                        type: object
                        properties:
                          rating:
                            type: integer
                          date:
                            type: integer
                      lowest:
                        type: object
                        properties:
                          rating:
                            type: integer
                          date:
                            type: integer
                  puzzle_rush:
                    type: object
                    properties:
                      best:
                        type: object
                        properties:
                          score:
                            type: integer
                          total_attempts:
                            type: integer
  /player/{username}/games/{year}/{month}:
    get:
      summary: Get monthly archives
      description: Get monthly archives
      operationId: getMonthlyArchives
      parameters:
        - name: username
          in: path
          description: The username of the player
          required: true
          schema:
            type: string
        - name: year
          in: path
          description: The year of the archive
          required: true
          schema:
            type: integer
        - name: month
          in: path
          description: The month of the archive
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  games:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                        pgn:
                          type: string
                        time_control:
                          type: string
                        end_time:
                          type: integer
                        rated:
                          type: boolean
                        tcn:
                          type: string
                        uuid:
                          type: string
                        initial_setup:
                          type: string
                        fen:
                          type: string
                        start_time:
                          type: integer
                        time_class:
                          type: string
                        rules:
                          type: string
                        white:
                          properties:
                            rating:
                              type: integer
                            result:
                              type: string
                            username:
                              type: string
                            uuid:
                              type: string
                        black:
                          properties:
                            rating:
                              type: integer
                            result:
                              type: string
                            username:
                              type: string
                            uuid:
                              type: string

components:
  schemas:
    stats:
      properties:
        last:
          type: object
          properties:
            rating:
              type: integer
            date:
              type: integer
            rd:
              type: integer
        best:
            type: object
            properties:
              rating:
                type: integer
              date:
                type: integer
              game:
                type: string
        record:
          type: object
          properties:
            win:
              type: integer
            loss:
              type: integer
            draw:
              type: integer        
        tournament:
          type: object
          properties:
            count:
              type: integer
            highest_finish:
              type: integer
            withdraw:
              type: integer
            points:
              type: integer