// <auto-generated/>
using Honlsoft.Chess.ChessDotCom.Player.Item.Games.Item.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Honlsoft.Chess.ChessDotCom.Player.Item.Games.Item {
    /// <summary>
    /// Builds and executes requests for operations under \player\{username}\games\{year}
    /// </summary>
    public class WithYearItemRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the Honlsoft.Chess.ChessDotCom.player.item.games.item.item collection</summary>
        /// <param name="position">The month of the archive</param>
        public WithMonthItemRequestBuilder this[int position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("month", position);
            return new WithMonthItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>Gets an item from the Honlsoft.Chess.ChessDotCom.player.item.games.item.item collection</summary>
        /// <param name="position">The month of the archive</param>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public WithMonthItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("month", position);
            return new WithMonthItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new WithYearItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithYearItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/player/{username}/games/{year}", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new WithYearItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithYearItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/player/{username}/games/{year}", rawUrl) {
        }
    }
}
